# tetris-deployment.yaml

apiVersion: apps/v1
kind: Rollout
metadata:
  name: tetris-deployment
spec:
  replicas: 5
  strategy:
    canary:
      stableService: tetris-stable
      canaryService: tetris-canary
      steps:
      - setWeight: 50
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: log1cdk/tetris
          ports:
            - containerPort: 80
